### ISSUE TITLE
Create TODO item

### ISSUE THREAD

**Issue by micuentadecasa** [hoomano/mojodex#7]
I told the assistant to create task/todo to do something in half hour, then it told me that it cannot use other services like google or similar to create the task, my main idea es if you have an assistant and a TODO list, the more reasonable thing is that it add a TODO item when you ask for creating a reminder; anyway then I started to ask it about the mojodex app and how to add a task, it suggested me to do it in the mobile app, then in the web app, but in the web app there is no button to add new TODOs..

**Comment by KellyRousselHoomano** [comment]
Hi @micuentadecasa,
Thank you for your interest in Mojodex and for raising this issue. Your feedback is valuable to us as we continue to improve and refine our system.
I see that you experienced some confusion regarding the TODO functionality. Let me address your points and hopefully provide some clarity:
* I’m currently updating our [TODO feature’s documentation](https://github.com/hoomano/mojodex/tree/to-do-list-doc/docs/to-do_list), which outlines the philosophy behind our approach to task management within the platform. I encourage you to take a look as it might provide a better understanding of the technical flow and the rationale behind our design choices.
* To summarize what’s in the doc: the feature is about relieving users of the mental load associated with managing their TODO lists. The initial concept was to empower the assistant to handle task management, allowing users to be hands-free in this regard.
* Moreover, it seems like there might have been some confusion regarding the interaction model. Our platform operates within task-specific chats rather than a general chat interface. This means that the assistant's capabilities are scoped to the context of the task at hand. As I write this, I realize that the "General assistance" task can be confusing in this context. Is this the task you tried to use to request a todo addition? This would really help me understand your experience 😊

Given these details, do you still think letting users add TODOs by themselves would be relevant? Your input on this matter would be greatly appreciated as we strive to enhance the user experience.
